name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Checkout do código
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Passo 2: Configura Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # ou 18, dependendo do seu projeto

      # Passo 3: Instala dependências
      - name: Install dependencies
        run: npm ci  # ou npm install

      # Passo 4: Executa Semantic Release
      - name: Semantic Release
        run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
